import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Menu } from "@/components/Menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Manual SIG-HOVET",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="overscroll-none">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overscroll-none`}

        style={{
          background: "linear-gradient(135deg, #8bc4b0 0%, #5da88c 25%, #3d8f72 50%, #2a7d5f 75%, #0a5a4b 100%)"
        }}
      >
        <Menu />
        <main className="flex items-start justify-center min-h-screen pt-8 pb-16">
          {children}
        </main>
      </body>
    </html>
  );
}
